# Generated by Django 4.0.1 on 2022-01-29 00:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aplicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_app', models.CharField(max_length=30)),
                ('desc_app', models.CharField(max_length=255)),
                ('celula', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Incidentes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_inc', models.CharField(max_length=10)),
                ('titulo_inc', models.CharField(max_length=100)),
                ('rep_inc', models.CharField(max_length=20)),
                ('desc_inc', models.CharField(max_length=255)),
                ('horainicio', models.DateTimeField(db_column='HoraInicio')),
                ('horafin', models.DateTimeField(blank=True, db_column='HoraFin', null=True)),
                ('esc_inc', models.CharField(max_length=50)),
                ('critico', models.BooleanField()),
                ('app_inc', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='chat_incidentes.aplicacion')),
            ],
        ),
    ]
