# Generated by Django 4.0.1 on 2022-02-09 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_incidentes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Areas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_area', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='aplicacion',
            name='desc_app',
            field=models.CharField(max_length=255, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='incidentes',
            name='num_inc',
            field=models.CharField(max_length=15),
        ),
    ]
